Repository ska-sa/katgui, pull requests merged in 2020-10, with the labels that each got.

#571 Hotfix V27: Fix rainfall display on Gui
  app/weather/weather.js
Labels: Still need dist files, busy reviewing

#569 Prepend label for sub band centre frequencies
  app/scheduler/scheduler-home.js
  app/scheduler/templates/subarray-config-container.html
  dist/app.full.min.1601629587279.css
  dist/app.full.min.1601629587279.js
  dist/index.html
  dist/version.txt
Labels: WIP

#578 Adds support for developing the GUI in a containerised environment
  Dockerfile
  Jenkinsfile
  Makefile
  README.md
  docker-compose.yml
  update.sh
Labels: busy reviewing
